HEADER = libft.h

OBJECT = ft_atoi.o ft_lstmap.o ft_putstr.o ft_strmapi.o ft_lstmap.o	ft_putstr_fd.o\
		ft_strncat.o ft_lstnew.o ft_strcat.o ft_strncmp.o ft_bzero.o ft_memalloc.o\
		ft_strchr.o ft_strncpy.o ft_isalnum.o ft_memccpy.o ft_strclr.o ft_strndup.o\
		ft_isalpha.o ft_memchr.o ft_strcmp.o ft_strnequ.o ft_isascii.o ft_memcmp.o\
		ft_strcpy.o ft_strnew.o ft_isblank.o ft_memcpy.o ft_strdel.o ft_strnstr.o\
		ft_isdigit.o ft_memdel.o ft_strdup.o ft_strrchr.o ft_isnumber.o ft_memmove.o\
		ft_strequ.o ft_strsplit.o ft_isprint.o ft_memset.o ft_striter.o ft_strstr.o\
		ft_isupper.o ft_putchar.o ft_striteri.o ft_strsub.o ft_itoa.o ft_putchar_fd.o\
		ft_strjoin.o ft_strtrim.o ft_lstadd.o ft_putendl.o ft_strlcat.o ft_tolower.o\
		ft_lstdel.o ft_putendl_fd.o ft_lst_size.o ft_toupper.o ft_lstdelone.o\
		ft_putnbr.o ft_strlen.o ft_lstiter.o ft_putnbr_fd.o ft_strmap.o

NAME = libft.a

all: $(NAME)

$(NAME): $(OBJECT)
	ar rc $(NAME) $(OBJECT) $(HEADER)

ft_lstmap.o: ft_lstmap.c
	@gcc -c -Wall -Wextra -Werror ft_lstmap.c

ft_lstiter.o: ft_lstiter.c
	@gcc -c -Wall -Wextra -Werror ft_lstiter.c

ft_lstadd.o: ft_lstadd.c
	@gcc -c -Wall -Wextra -Werror ft_lstadd.c

ft_lstdel.o: ft_lstdel.c
	@gcc -c -Wall -Wextra -Werror ft_lstdel.c

ft_lstdelone.o: ft_lstdelone.c
	@gcc -c -Wall -Wextra -Werror ft_lstdelone.c

ft_lstnew.o: ft_lstnew.c
	@gcc -c -Wall -Wextra -Werror ft_lstnew.c

ft_bzero.o: ft_bzero.c
	@gcc -c -Wall -Wextra -Werror ft_bzero.c

ft_isalnum.o: ft_isalnum.c
	@gcc -c -Wall -Wextra -Werror ft_isalnum.c

ft_isalpha.o: ft_isalpha.c
	@gcc -c -Wall -Wextra -Werror ft_isalpha.c

ft_isascii.o: ft_isascii.c
	@gcc -c -Wall -Wextra -Werror ft_isascii.c

ft_isdigit.o: ft_isdigit.c
	@gcc -c -Wall -Wextra -Werror ft_isdigit.c

ft_isprint.o: ft_isprint.c
	@gcc -c -Wall -Wextra -Werror ft_isprint.c

ft_memcpy.o: ft_memcpy.c
	@gcc -c -Wall -Wextra -Werror ft_memcpy.c

ft_memcmp.o: ft_memcmp.c
	@gcc -c -Wall -Wextra -Werror ft_memcmp.c

ft_memchr.o: ft_memchr.c
	@gcc -c -Wall -Wextra -Werror ft_memchr.c

ft_memccpy.o: ft_memccpy.c
	@gcc -c -Wall -Wextra -Werror ft_memccpy.c

ft_memmove.o: ft_memmove.c
	@gcc -c -Wall -Wextra -Werror ft_memmove.c

ft_memset.o: ft_memset.c
	@gcc -c -Wall -Wextra -Werror ft_memset.c

ft_strcmp.o: ft_strcmp.c
	@gcc -c -Wall -Wextra -Werror ft_strcmp.c

ft_strncmp.o: ft_strncmp.c
	@gcc -c -Wall -Wextra -Werror ft_strncmp.c

ft_strcat.o: ft_strcat.c
	@gcc -c -Wall -Wextra -Werror ft_strcat.c

ft_strncat.o: ft_strncat.c
	@gcc -c -Wall -Wextra -Werror ft_strncat.c

ft_strchr.o: ft_strchr.c
	@gcc -c -Wall -Wextra -Werror ft_strchr.c

ft_strrchr.o: ft_strrchr.c
	@gcc -c -Wall -Wextra -Werror ft_strrchr.c

ft_strcpy.o: ft_strcpy.c
	@gcc -c -Wall -Wextra -Werror ft_strcpy.c

ft_strdup.o: ft_strdup.c
	@gcc -c -Wall -Wextra -Werror ft_strdup.c

ft_strlcat.o: ft_strlcat.c
	@gcc -c -Wall -Wextra -Werror ft_strlcat.c

ft_strlen.o: ft_strlen.c
	@gcc -c -Wall -Wextra -Werror ft_strlen.c

ft_strncpy.o: ft_strncpy.c
	@gcc -c -Wall -Wextra -Werror ft_strncpy.c

ft_strstr.o: ft_strstr.c
	@gcc -c -Wall -Wextra -Werror ft_strstr.c

ft_strnstr.o: ft_strnstr.c
	@gcc -c -Wall -Wextra -Werror ft_strnstr.c

ft_tolower.o: ft_tolower.c
	@gcc -c -Wall -Wextra -Werror ft_tolower.c

ft_toupper.o: ft_toupper.c
	@gcc -c -Wall -Wextra -Werror ft_toupper.c

ft_atoi.o: ft_atoi.c
	@gcc -c -Wall -Wextra -Werror ft_atoi.c

ft_memalloc.o: ft_memalloc.c
	@gcc -c -Wall -Wextra -Werror ft_memalloc.c

ft_memdel.o: ft_memdel.c
	@gcc -c -Wall -Wextra -Werror ft_memdel.c

ft_strnew.o: ft_strnew.c
	@gcc -c -Wall -Wextra -Werror ft_strnew.c

ft_strdel.o: ft_strdel.c
	@gcc -c -Wall -Wextra -Werror ft_strdel.c

ft_strclr.o: ft_strclr.c
	@gcc -c -Wall -Wextra -Werror ft_strclr.c

ft_striter.o: ft_striter.c
	@gcc -c -Wall -Wextra -Werror ft_striter.c

ft_striteri.o: ft_striteri.c
	@gcc -c -Wall -Wextra -Werror ft_striteri.c

ft_strmap.o: ft_strmap.c
	@gcc -c -Wall -Wextra -Werror ft_strmap.c

ft_strmapi.o: ft_strmapi.c
	@gcc -c -Wall -Wextra -Werror ft_strmapi.c

ft_strequ.o: ft_strequ.c
	@gcc -c -Wall -Wextra -Werror ft_strequ.c

ft_strnequ.o: ft_strnequ.c
	@gcc -c -Wall -Wextra -Werror ft_strnequ.c

ft_strsub.o: ft_strsub.c
	@gcc -c -Wall -Wextra -Werror ft_strsub.c

ft_strjoin.o: ft_strjoin.c
	@gcc -c -Wall -Wextra -Werror ft_strjoin.c

ft_strtrim.o: ft_strtrim.c
	@gcc -c -Wall -Wextra -Werror ft_strtrim.c

ft_strsplit.o: ft_strsplit.c
	@gcc -c -Wall -Wextra -Werror ft_strsplit.c

ft_putchar.o: ft_putchar.c
	@gcc -c -Wall -Wextra -Werror ft_putchar.c

ft_putstr.o: ft_putstr.c
	@gcc -c -Wall -Wextra -Werror ft_putstr.c

ft_putendl.o: ft_putendl.c
	@gcc -c -Wall -Wextra -Werror ft_putendl.c

ft_putchar_fd.o: ft_putchar_fd.c
	@gcc -c -Wall -Wextra -Werror ft_putchar_fd.c

ft_putstr_fd.o: ft_putstr_fd.c
	@gcc -c -Wall -Wextra -Werror ft_putstr_fd.c

ft_putendl_fd.o: ft_putendl_fd.c
	@gcc -c -Wall -Wextra -Werror ft_putendl_fd.c

ft_putnbr.o: ft_putnbr.c
	@gcc -c -Wall -Wextra -Werror ft_putnbr.c

ft_putnbr_fd.o: ft_putnbr_fd.c
	@gcc -c -Wall -Wextra -Werror ft_putnbr_fd.c

ft_itoa.o: ft_itoa.c
	@gcc -c -Wall -Wextra -Werror ft_itoa.c

ft_memdup.o: ft_memdup.c
	@gcc -c -Wall -Wextra -Werror ft_memdup.c

ft_strndup.o: ft_strndup.c
	@gcc -c -Wall -Wextra -Werror ft_strndup.c

ft_isblank.o: ft_isblank.c
	@gcc -c -Wall -Wextra -Werror ft_isblank.c

ft_isnumber.o: ft_isnumber.c
	@gcc -c -Wall -Wextra -Werror ft_isnumber.c

ft_isupper.o: ft_isupper.c
	@gcc -c -Wall -Wextra -Werror ft_isupper.c

ft_lst_size.o: ft_lst_size.c
	@gcc -c -Wall -Wextra -Werror ft_lst_size.c

clean:
	rm -f $(OBJECT)

fclean: clean
	rm -f $(NAME)

re: fclean all
